# Copyright © SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "sixtyfps-interpreter"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Interpreter library for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
categories = ["gui", "rendering::engine"]
keywords = ["gui", "toolkit", "graphics", "design", "ui"]

[lib]
path = "lib.rs"

[features]

# Default features
default = ["backend-gl", "x11", "backend-qt", "compat-0-2-0"]

# Mandatory feature:
# This feature is required to keep the compatibility with SixtyFPS 0.2.0
# Newer patch version may put current functionality behind a new feature
# that would be enabled by default only if this feature was added
compat-0-2-0 = []

# Ability to print the diagnostics on std out
display-diagnostics = ["sixtyfps-compilerlib/display-diagnostics"]

# Enable the FFI to be used with C++
ffi = ["spin_on", "sixtyfps-corelib/ffi"]

# Backends
x11 = ["sixtyfps-rendering-backend-default/x11"]
wayland = ["sixtyfps-rendering-backend-default/wayland"]
backend-gl = ["sixtyfps-rendering-backend-default/sixtyfps-rendering-backend-gl"]
backend-qt = ["sixtyfps-rendering-backend-default/sixtyfps-rendering-backend-qt"]


[dependencies]
sixtyfps-corelib = { version = "=0.2.0", path = "../corelib", features = ["rtti"] }
sixtyfps-rendering-backend-default = { version = "=0.2.0", path = "../../sixtyfps_runtime/rendering_backends/default" }
vtable = { version = "0.1.1", path="../../helper_crates/vtable" }
sixtyfps-compilerlib = { version = "=0.2.0", path = "../../sixtyfps_compiler" }
lyon_path = { version = "0.17.3" }
derive_more = "0.99.5"
generativity = "1"
once_cell = "1.5"
thiserror = "1"

[dependencies.spin_on]
version = "0.1"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
sixtyfps-rendering-backend-gl = { version = "=0.2.0", path = "../../sixtyfps_runtime/rendering_backends/gl" }

[dev-dependencies]
spin_on = "0.1"
sixtyfps-rendering-backend-testing = { path = "../../sixtyfps_runtime/rendering_backends/testing" }

[package.metadata.docs.rs]
features = ["display-diagnostics"]
